name: Lint/Format CI

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          OLLAMA_URL: ${{ secrets.OLLAMA_URL }}
          ENV: ${{ secrets.ENV }}

        steps:
          - name: Checkout repo
            uses: actions/checkout@v4

          - name: Python setup
            uses: actions/setup-python@v5
            with:
                python-version: "3.12"

          - name: Install dependencies
            run: pip install -r requirements.txt 
            
          - name: Run flake8
            run: flake8