name: Tests CI

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          OLLAMA_URL: ${{ secrets.OLLAMA_URL }}
          ENV: ${{ secrets.ENV }}

        services:
          ollama:
            image: ollama/ollama
            ports:
              - 11434:11434

        steps:
          - name: Checkout repo
            uses: actions/checkout@v4

          - name: Install ollama CLI
            run: curl -fsSL https://ollama.ai/install.sh | sh

          - name: Install ollama model
            run: ollama pull mistral:7b-instruct

          - name: Python setup
            uses: actions/setup-python@v5
            with:
                python-version: "3.12"

          - name: Install dependencies
            run: pip install -r requirements.txt 

          - name: Run tests
            env:
                PYTHONPATH: .
            run: pytest